version: 2

#Do for the package dependencies

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]



