name: SonarQube Analysis
on:
    # Trigger analysis when pushing to your main branches, and when creating a pull request.
    push:
        branches:
            - main
            - "feature/**"
            - "releases/**"
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    sonarqube:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  # Disabling shallow clones is recommended for improving the relevancy of reporting
                  fetch-depth: 0
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
